# 币安API配置
# 请将以下值替换为您的实际API密钥
# 注意：请妥善保管您的API密钥，不要泄露给他人

api_key: "your_api_key_here"
api_secret: "your_api_secret_here"

# 可选配置
testnet: false  # 设置为true使用测试网络
sandbox: false  # 设置为true使用沙盒环境

# 安全提示：
# 1. 请确保API密钥具有交易权限
# 2. 建议设置IP白名单
# 3. 定期更换API密钥
# 4. 不要将API密钥提交到版本控制系统 