# 阿翔趋势交易系统配置文件

# 交易设置
trading:
  symbol: "BTC/USDT:USDT"  # 交易对
  timeframe: "1h"          # K线周期 (1m, 5m, 15m, 1h, 4h, 1d, etc.)
  is_futures: true         # 是否为合约交易

# 资金设置
capital:
  initial_capital: 10000    # 初始资金 (USDT)
  leverage: 3               # 杠杆倍数
  risk_per_trade: 0.02      # 每笔交易风险比例 (0.02 = 2%)

# 指标参数
indicators:
  dema144_len: 144         # DEMA144均线周期
  dema169_len: 169         # DEMA169均线周期
  ema120_len: 120          # EMA120均线周期
  ema200_len: 200          # EMA200均线周期
  atr_period: 34           # ATR计算周期
  atr_multiplier: 3.0      # ATR倍数

# 网络设置
network:
  http_proxy: "http://127.0.0.1:7897"  # HTTP代理
  https_proxy: "http://127.0.0.1:7897" # HTTPS代理

# 数据设置
data:
  default_lookback_days: 30  # 默认回溯天数
  max_candles: 1000          # 最大K线数量限制 