capital:
  initial_capital: 10000.0
  leverage: 3.0
  risk_per_trade: 1.0
indicators:
  atr_multiplier: 3.0
  atr_period: 34
  dema144_len: 144
  dema169_len: 169
  ema120_len: 120
  ema200_len: 200
network:
  http_proxy: http://127.0.0.1:7897
  https_proxy: http://127.0.0.1:7897
trading:
  is_futures: true
  symbol: BTC/USDT:USDT
  timeframe: 1h
